name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jetli/wasm-pack-action@v0.4.0
    - name: Cargo install
      run: cargo install --locked cargo-deny tickbox
    - name: Install rust wasm32
      run: rustup target add wasm32-unknown-unknown
    - name: Install nightly rustfmt
      run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt clippy
    - name: Run tests
      run: NODIFF=true CLEANUP=true tickbox --dir tickbox/pre-commit --disable-tui --max-concurrency=1
